on:
  workflow_dispatch:
  
  push:
    paths:
    - .github/workflows/approve.yml
env:
 OWNER: XpiritBV
 REPO: Deployment-protection-rule-demo
 ENVIRONMENT_NAME: demo-2
 RUNID: 4766867724

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ vars.APP_ID }}
          application_private_key: ${{ secrets.APP_SECRET }}

      - name: Get deployment rules
        env:
          token: ${{ steps.get_workflow_token.outputs.token }}
        run: |
            url="https://api.github.com/repos/$OWNER/$REPO/environments/$ENVIRONMENT_NAME/deployment_protection_rules"
            echo "$url"
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $token"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url $url
            
      - name: Get deployment rule
        env:
          token: ${{ steps.get_workflow_token.outputs.token }}
        run: |
            url="https://api.github.com/repos/$OWNER/$REPO/environments/actions/runs/$RUNID/pending_deployments"
            echo "$url"
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $token"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url $url
            
      - name: Post deployment rule status
        env:
          token: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          url="https://api.github.com/repos/$OWNER/$REPO/actions/runs/$RUNID/deployment_protection_rule"
          echo "$url"
            curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $token"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"environment_name":"$ENVIRONMENT_NAME","state":"approved","comment":"All checks passed :rocket:."}' \
            --url $url
